SELECT * FROM EMP e 

SELECT COUNT(*) 
FROM EMP e 

SELECT COUNT(SAL) 
FROM EMP e 

SELECT COUNT(SAL) 
FROM EMP e 
WHERE job = 'SALESMAN'

SELECT COUNT(SAL), SUM(SAL), AVG(SAL), MIN(SAL) , MAX(SAL) 
FROM EMP e 
WHERE JOB = 'SALESMAN'

SELECT JOB, COUNT(SAL), SUM(SAL), AVG(SAL), MIN(SAL) , MAX(SAL) 
FROM EMP e 
GROUP BY JOB
ORDER BY JOB 

SELECT JOB, COUNT(SAL), SUM(SAL), AVG(SAL), MIN(SAL) , MAX(SAL) 
FROM EMP e 
GROUP BY JOB
HAVING COUNT(SAL) >= 4
ORDER BY JOB DESC 

--1
SELECT COUNT(*) 
FROM EMP e 

--2
SELECT COUNT(*) 
FROM EMP e 
WHERE DEPTNO = 20 OR MGR <= 7700

--3
SELECT MIN(SAL) 
FROM EMP e 
WHERE DEPTNO = 10 OR DEPTNO = 20

--4
SELECT MIN(SAL) , MAX(SAL) , SUM(SAL) 
FROM EMP e 

--5
SELECT DEPTNO, AVG(SAL) FROM EMP e 
GROUP BY DEPTNO

--6
SELECT DEPTNO, SUM(SAL) FROM EMP e 
GROUP BY DEPTNO
ORDER BY DEPTNO

--7
SELECT DEPTNO, avg(SAL) FROM EMP e 
GROUP BY DEPTNO
HAVING AVG(SAL) >= 2000
ORDER BY DEPTNO DESC 

--8
SELECT COUNT(*), AVG(SAL)  FROM EMP e 
WHERE JOB = 'MANAGER'

--9
SELECT COUNT(ENAME) FROM EMP e 
WHERE ENAME LIKE ('%S%')

--10
SELECT COUNT(SAL) FROM EMP e
WHERE SAL >= 3000 AND COMM IS NOT NULL
ORDER BY SAL DESC 