SELECT * FROM EMP e 

--1
SELECT LENGTH(ENAME) FROM EMP e 

--2
SELECT LENGTH(ENAME) FROM EMP e 
WHERE JOB = 'MANAGER'

--3
SELECT ENAME, JOB FROM EMP e 
WHERE COMM IS NULL 

--4
SELECT HIREDATE FROM EMP e 
WHERE COMM IS NOT NULL 

--5
SELECT SUBSTR(ENAME, 2) FROM EMP e 

--6
SELECT SUBSTR(JOB, 1, 3) FROM EMP e 

--7
SELECT REPLACE(ENAME, 'K', 'P') FROM EMP e 

--8
SELECT EMPNO ||  '번은 ' || ename || '입니다' AS RESULT FROM EMP e 

--9
SELECT HIREDATE, TO_CHAR(HIREDATE, 'MONTH') AS 입사월, TO_CHAR(HIREDATE, 'DAY') AS 입사요일 FROM EMP e 

--10
SELECT job, 
CASE job
WHEN 'MANAGER' THEN 'level1'
WHEN 'SALESMAN' THEN 'level2'
ELSE 'level3'
END AS level_result
FROM EMP e 