CREATE TABLE PRODUCT3(
"ID" VARCHAR2(200),
"NAME" VARCHAR2(200),
"CONTENT" VARCHAR2(200),
"PRICE" VARCHAR2(200),
"COMPANY" VARCHAR2(200),
"IMG" VARCHAR2(200)
)

SELECT * FROM PRODUCT3 p 

--2
SELECT * FROM PRODUCT3
ORDER BY PRICE DESC

--3
SELECT NAME, CONTENT, PRICE FROM PRODUCT3
ORDER BY COMPANY

--4
SELECT  DISTINCT COMPANY FROM PRODUCT3

--5
SELECT price * 5 AS "price5" FROM PRODUCT3

--6
SELECT name, company FROM PRODUCT3
WHERE PRICE = 5000

--7
SELECT name, price, company FROM PRODUCT3
WHERE PRICE BETWEEN 3000 AND 6000

--8
SELECT company, name FROM PRODUCT3
WHERE NOT COMPANY = 'c100'

--9
SELECT name, PRICE FROM PRODUCT3
WHERE COMPANY = 'c100' OR COMPANY = 'c200'

--10
SELECT * FROM PRODUCT3
WHERE NAME LIKE '%4'

--11
SELECT * FROM PRODUCT3
WHERE CONTENT LIKE '%food%'

--12
UPDATE PRODUCT3 SET CONTENT = '품절'
WHERE PRICE = 5000

--13
UPDATE PRODUCT3 SET IMG = 'o.png', PRICE = 10000
WHERE ID = '100' OR ID = '102'

--14
DELETE FROM PRODUCT3
WHERE COMPANY = 'c100'

--15
DELETE FROM PRODUCT3