CREATE TABLE "HR"."BBS" 
   (	"no" VARCHAR2(100), 
	"TITLE" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"WRITER" VARCHAR2(100)
	)
	
CREATE TABLE "HR"."MEMBER0" 
   (	"ID" VARCHAR2(100), 
	"PW" VARCHAR2(100), 
	"NAME" VARCHAR2(100), 
	"TEL" VARCHAR2(100)
   )
   
CREATE TABLE "HR"."PRODUCT0" 
   (	"ID" VARCHAR2(200), 
	"NAME" VARCHAR2(200), 
	"CONTENT" VARCHAR2(200), 
	"PRICE" VARCHAR2(200), 
	"COMPANY" VARCHAR2(200), 
	"IMG" VARCHAR2(200)
   )
	
	
--	한줄복사: 컨트롤 + 알트 + 화살표 아래

--	한줄삭제: 컨트롤 + D
	
--  저장할 대상: 엔티티(회원정보, 게시판, 상품), 엔티티간의 관계: 회원이 상품을 주문하다(주문정보)
--			  엔티티 + 관계 --> 테이블로 만들자!!!
	
CREATE TABLE orderlist (
	"no" varchar2(100),
	"member_id" varchar2(100),
	"product_id" varchar2(100),
	"total_count" varchar2(100)
)

CREATE TABLE "HR"."BBS2" 
(	"no" VARCHAR2(100), 
	"TITLE" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"WRITER" VARCHAR2(100), 
	 CONSTRAINT "BBS_PK22" PRIMARY KEY ("no"),
	 CONSTRAINT "FK_MEMBER22" FOREIGN KEY ("WRITER")
	  REFERENCES "HR"."MEMBER" ("ID")
)

CREATE TABLE "HR"."BBS3" 
(	"no" VARCHAR2(100), 
	"TITLE" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"WRITER" VARCHAR2(100)
)

ALTER TABLE HR.BBS3
ADD CONSTRAINT BBS3_PK 
PRIMARY KEY ("no")

ALTER TABLE HR.BBS3 
ADD CONSTRAINT FK_MEMBER33 
FOREIGN KEY (WRITER) REFERENCES HR."MEMBER"(ID);

CREATE TABLE "HR"."DEPART2" 
( "ID" VARCHAR2(100), 
"NAME" VARCHAR2(100), 
"INSTRUCTOR" VARCHAR2(100), 
 CONSTRAINT "DEPART2_PK" PRIMARY KEY ("ID")
)

CREATE TABLE "HR"."STUDENT2" 
("ID" VARCHAR2(100), 
 "NAME" VARCHAR2(100) NOT NULL ENABLE, 
 "TEL" VARCHAR2(100), 
 "DEPART_ID" VARCHAR2(100) 
)

ALTER TABLE hr.student2
ADD CONSTRAINT student2_PK
PRIMARY KEY ("ID")
ADD CONSTRAINT fk_student2
FOREIGN KEY (depart_id) REFERENCES HR."DEPART2"(ID)

CREATE TABLE member22
AS SELECT * FROM "member" m 

INSERT INTO MEMBER22
VALUES ('banana3','banana3','banana3','banana3', sysdate)

SELECT * FROM MEMBER22 m 

INSERT INTO MEMBER22
VALUES ('banana3','banana3','banana3','banana3', sysdate, 'aaa')

INSERT INTO BBS 
VALUES (BBS_ID_SEQ.nextval, 'happ2', 'happy day2', 'ice')

SELECT * FROM BBS b 

CREATE SEQUENCE pd_id_seq INCREMENT BY 1 START WITH 1

CREATE TABLE product (
	id number(38, 0),
	name varchar2(100)
)

INSERT INTO product
VALUES (PD_ID_SEQ.nextval, 'happy')

SELECT * FROM product

CREATE TABLE orderlist (
	id number(38, 0),
	title varchar2(100),
	price number(38, 0)
)

CREATE SEQUENCE or_seq INCREMENT BY 1 START WITH 1

INSERT INTO orderlist
VALUES (OR_SEQ.nextval, 'c', '2000')

SELECT * FROM ORDERLIST o 
ORDER BY id

SELECT * FROM ORDERLIST o 
WHERE id >= 3
ORDER BY id DESC

CREATE TABLE DEPT
(
DEPTNO NUMBER(2),
DNAME VARCHAR2(14 BYTE),
LOC VARCHAR2(13 BYTE)
)

CREATE TABLE EMP
(
EMPNO NUMBER(4),
ENAME VARCHAR2(10 BYTE),
JOB VARCHAR2(9 BYTE),
MGR NUMBER(4),
HIREDATE DATE,
SAL NUMBER(7,2),
COMM NUMBER(7,2),
DEPTNO NUMBER(2)
)

CREATE TABLE SALGRADE
(
GRADE NUMBER,
LOSAL NUMBER,
HISAL NUMBER
)

ALTER TABLE DEPT ADD (
CONSTRAINT PK_DEPT
PRIMARY KEY(DEPTNO)
)

 
ALTER TABLE EMP ADD (
CONSTRAINT PK_EMP
PRIMARY KEY
(EMPNO)
)

 
ALTER TABLE EMP ADD (
CONSTRAINT FK_DEPTNO
FOREIGN KEY (DEPTNO)
REFERENCES DEPT (DEPTNO)
)

SELECT * FROM EMP e -- selection

SELECT deptno FROM EMP e -- projection

SELECT DISTINCT deptno FROM EMP e -- 중복제거

SELECT ename, sal * 12 FROM EMP e 

SELECT * FROM EMP e 
ORDER BY sal DESC 

SELECT * FROM EMP e 
WHERE DEPTNO = 30
ORDER BY EMPNO DESC 

SELECT * FROM EMP e 
WHERE DEPTNO = 30 AND JOB = 'SALESMAN'

SELECT * FROM EMP e 
WHERE DEPTNO = 30 OR  JOB = 'SALESMAN'

SELECT * FROM EMP e 
WHERE sal >= 3000

SELECT * FROM EMP e 
WHERE sal != 3000

SELECT * FROM EMP e 
WHERE job IN ('SALESMAN', 'MANAGER')
ORDER BY JOB 

SELECT * FROM EMP e 
WHERE sal BETWEEN 2000 AND 3000
ORDER BY EMPNO

SELECT * FROM EMP e 
WHERE sal NOT BETWEEN 2000 AND 3000
ORDER BY EMPNO

SELECT * FROM EMP e 
WHERE ENAME LIKE '_L%'

SELECT * FROM EMP e 
WHERE ENAME NOT LIKE '_L%'

SELECT * FROM EMP e 
WHERE comm IS NULL 

SELECT * FROM EMP e 
WHERE comm IS NOT NULL 

CREATE TABLE DEPT_TEMP2
AS SELECT * FROM DEPT

SELECT * FROM DEPT_TEMP2

UPDATE DEPT_TEMP2 SET LOC = 'SEOUL'

UPDATE DEPT_TEMP2 SET DNAME = 'DATABASE', loc = 'BUSAN' WHERE DEPTNO = 40

DELETE FROM DEPT_TEMP2 dt WHERE DNAME = 'SALES'

SELECT * FROM DEPT_TEMP2

